name: Build Static Website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material 'mkdocstrings[python]' black
          pip install zvec
          npm ci

      - name: Build API References
        run: |
          cd ./api-reference
          cd ./python-api
          mkdocs build
          cd ../nodejs-api
          npm install
          cp node_modules/@zvec/zvec/src/index.d.ts ./
          npx typedoc
          cd ..

      - name: Build Website
        run: |
          npm run build

      - name: List Output Files
        run: |
          echo "Build output directory listing:"
          ls -la ./out/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          cname: zvec.org
          force_orphan: true
